package com.example.demo;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.Arrays;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Smoke tests generated by AutoTestForge in offline mode.
 * They pin the public contract of {@link PriceCalculator}; switch to an LLM provider
 * (ollama / openai / anthropic) for behavioral scenarios.
 */
class PriceCalculatorTest {

    @Test
    @DisplayName("type is loadable and concrete")
    void class_shouldBeLoadableAndConcrete() {
        Class<?> type = PriceCalculator.class;

        assertThat(type).isNotNull();
        assertThat(Modifier.isInterface(type.getModifiers())).isFalse();
    }

    @Test
    @DisplayName("public API declares total")
    void total_shouldBeDeclaredAsPublicMethod() {
        Method[] methods = PriceCalculator.class.getMethods();

        boolean declared = Arrays.stream(methods)
                .anyMatch(method -> method.getName().equals("total"));

        assertThat(declared).isTrue();
    }

    @Test
    @DisplayName("public API declares isEligibleForFreeShipping")
    void isEligibleForFreeShipping_shouldBeDeclaredAsPublicMethod() {
        Method[] methods = PriceCalculator.class.getMethods();

        boolean declared = Arrays.stream(methods)
                .anyMatch(method -> method.getName().equals("isEligibleForFreeShipping"));

        assertThat(declared).isTrue();
    }
}
