package com.example.demo;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.Arrays;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Smoke tests generated by AutoTestForge in offline mode.
 * They pin the public contract of {@link TextUtils}; switch to an LLM provider
 * (ollama / openai) for behavioral scenarios.
 */
class TextUtilsTest {

    @Test
    @DisplayName("class is loadable and public")
    void class_shouldBePublic() {
        assertThat(Modifier.isPublic(TextUtils.class.getModifiers())).isTrue();
    }

    @Test
    @DisplayName("public API declares reverse")
    void reverse_shouldBeDeclaredAsPublicMethod() {
        Method[] methods = TextUtils.class.getMethods();

        boolean declared = Arrays.stream(methods)
                .anyMatch(method -> method.getName().equals("reverse"));

        assertThat(declared).isTrue();
    }

    @Test
    @DisplayName("public API declares isPalindrome")
    void isPalindrome_shouldBeDeclaredAsPublicMethod() {
        Method[] methods = TextUtils.class.getMethods();

        boolean declared = Arrays.stream(methods)
                .anyMatch(method -> method.getName().equals("isPalindrome"));

        assertThat(declared).isTrue();
    }

    @Test
    @DisplayName("public API declares truncate")
    void truncate_shouldBeDeclaredAsPublicMethod() {
        Method[] methods = TextUtils.class.getMethods();

        boolean declared = Arrays.stream(methods)
                .anyMatch(method -> method.getName().equals("truncate"));

        assertThat(declared).isTrue();
    }
}
