package com.autotestforge.ai;

import com.autotestforge.core.domain.ExternalTestContext;
import com.autotestforge.core.domain.GeneratedTestFile;
import com.autotestforge.core.domain.JavaClassInfo;
import com.autotestforge.core.domain.MethodInfo;
import com.autotestforge.core.domain.ValidationResult;
import com.autotestforge.core.port.out.AiTestGeneratorPort;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Deterministic, LLM-free fallback generator (provider {@code offline}).
 * Produces reflection-based smoke tests that verify the public contract of the
 * class: useful for demos, CI environments without model access, and for
 * exercising the full pipeline (scan, write, validate) end-to-end.
 */
public class OfflineTestGenerator implements AiTestGeneratorPort {

    @Override
    public GeneratedTestFile generate(JavaClassInfo classInfo, String provider, ExternalTestContext externalContext) {
        String testClassName = classInfo.className() + "Test";
        String source = """
                package %s;

                import org.junit.jupiter.api.DisplayName;
                import org.junit.jupiter.api.Test;

                import java.lang.reflect.Method;
                import java.lang.reflect.Modifier;
                import java.util.Arrays;

                import static org.assertj.core.api.Assertions.assertThat;

                /**
                 * Smoke tests generated by AutoTestForge in offline mode.
                 * They pin the public contract of {@link %s}; switch to an LLM provider
                 * (ollama / openai) for behavioral scenarios.
                 */
                class %s {

                %s
                }
                """.formatted(
                classInfo.packageName(),
                classInfo.className(),
                testClassName,
                testMethods(classInfo));
        return new GeneratedTestFile(classInfo.packageName(), testClassName, source);
    }

    @Override
    public GeneratedTestFile fix(JavaClassInfo classInfo, GeneratedTestFile previousTest,
                                 ValidationResult validationResult, String provider,
                                 ExternalTestContext externalContext) {
        // Deterministic output: regenerating is the only "fix" available offline.
        return generate(classInfo, provider, externalContext);
    }

    private String testMethods(JavaClassInfo classInfo) {
        StringBuilder methods = new StringBuilder();
        methods.append("""
                    @Test
                    @DisplayName("class is loadable and public")
                    void class_shouldBePublic() {
                        assertThat(Modifier.isPublic(%s.class.getModifiers())).isTrue();
                    }
                """.formatted(classInfo.className()));

        Set<String> methodNames = classInfo.publicMethods().stream()
                .map(MethodInfo::name)
                .collect(Collectors.toCollection(LinkedHashSet::new));
        for (String methodName : methodNames) {
            methods.append(System.lineSeparator());
            methods.append("""
                        @Test
                        @DisplayName("public API declares %s")
                        void %s_shouldBeDeclaredAsPublicMethod() {
                            Method[] methods = %s.class.getMethods();

                            boolean declared = Arrays.stream(methods)
                                    .anyMatch(method -> method.getName().equals("%s"));

                            assertThat(declared).isTrue();
                        }
                    """.formatted(methodName, methodName, classInfo.className(), methodName));
        }
        return methods.toString().stripTrailing();
    }
}
